apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  
generatorOptions:
  disableNameSuffixHash: true
 
configMapGenerator:
- name: prod-nginx-config
  files:
  - configs/fake_config.py

commonLabels:
  app: nginx
